config/routes.rb
Zero::Application.routes.draw do
  resources :events

  devise_for :users
  resources :users

  resources :forums do 
    resources :subjects do
      resources :topics do
        resources :discusses do
          resources :posts
        end
      end
    end
  end
  
  resources :event_calendar
  resources :events do
    resources :rsvps
  end
  resources :home
  
  root 'home#index'

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: [:scoped, :slugged], scope: :subject
	
	belongs_to :subject, touch: true
	has_many :discusses
	belongs_to :user
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_subject_from_subject_id
  before_action :set_forum_from_forum_id
  before_action :set_user_from_current_user
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = @subject.topics.order('title ASC')
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new(subject_id: @subject)
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
       @topic = @subject.topics.new(topic_params)
       @topic.user = @user

    respond_to do |format|
      if @topic.save
        format.html { render action: 'show' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = @subject.topics.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:subject_id, :title, :description, :username)
    end
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @subject, @topic] do |f| %>
  <div class="col-xs-offset-0 col-sm-offset-2 col-xs-12 col-sm-8 form_body">
    <div class="field">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br>
      <%= f.text_area :description, size: "35x5" %>
    </div>
  </div>
  <div class="actions form_submit col-xs-offset-0 col-sm-offset-2 col-xs-12 col-sm-8">
    <br> 
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1 class="new_form">Edit A Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_subject_topics_path %>

app/views/topics/index.html.erb
<div class="forum_wrapper col-xs-offset-0 col-sm-offset-1 col-xs-12 col-sm-10">
  <% @topics.each do |topic| %>
    <div class="row forum_row">
      <div class="col-xs-2 forum_user">
        <%= link_to topic.user.username, user_path(topic.user) %>
      </div>
      <div class="col-xs-8 forum_area">
        <%= link_to topic.title, forum_subject_topic_discusses_path(topic_id: topic.slug) %>
        <br>
        <div>
          <%= topic.description %>
        </div>
      </div> 
      <div class="col-xs-2 forum_time">
        <%= time_ago_in_words(topic.updated_at) %> ago
        <% if current_user && current_user.admin %>
          <br>
          <%= link_to 'Destroy', forum_subject_topic_path(id: topic.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'Edit', edit_forum_subject_topic_path(id: topic.id) %>
        <% end %>
      </div>
      </br>
    </div>
  <% end %>
  <br>
</div>
<% if current_user %>
  <a href="<%= new_forum_subject_topic_path %>" class="btn btn-default col-sm-offset-10">New Topic</a>
<% end %>

app/views/topics/new.html.erb
<h1 class="new_form">Create A Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_subject_topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @topic.subject_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Back', forum_subject_topics_path %>