config/routes.rb
Zero::Application.routes.draw do
  resources :events

  devise_for :users
  resources :users

  resources :forums do 
    resources :subjects do
      resources :topics do
        resources :discusses do
          resources :posts
        end
      end
    end
  end
  
  resources :event_calendar
  resources :events do
    resources :rsvps
  end
  resources :home
  
  root 'home#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  extend FriendlyId
  friendly_id :username
  
  has_many :forums
  has_many :subjects
  has_many :topics
  has_many :discusses
  has_many :posts
  has_many :events
  has_many :rsvps
  has_many :events, through: :rsvps 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user && current_user.admin
      @users = User.all
    else
      redirect_to "/forums"
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @newest_posts = @user.posts.order("created_at DESC").limit(5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit  
    unless current_user == @user || (current_user && current_user.admin)
      redirect_to "/forums"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :admin, :email, :first_name, :last_name, :gender, :password, :password_confirmation, :remember_me)
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-xs-offset-0 col-sm-offset-4 col-xs-12 col-sm-4 user_body">
    <div class="field">
      <%= f.label :username %>
      <br>
      <%= f.text_field :username %>
      <br>
      <%= f.label :email %>
      <br>
      <%= f.text_field :email %>
      <br>
      <%= f.label :first_name %>
      <br>
      <%= f.text_field :first_name %>
      <br>
      <%= f.label :last_name %>
      <br>
      <%= f.text_field :last_name %>
      <br>
      <%= f.label :gender %>
      <br>
      <%= f.text_field :gender %>
      <br>
      <% if current_user && current_user.admin %>
        <%= f.label :admin %>
        <br>
        <%= f.check_box :admin %>
        <br>
      <% end %>
    </div>
  </div>
  <div class="actions form_submit col-xs-offset-0 col-sm-offset-6 col-xs-12 col-sm-2">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="new_form">Edit <%= current_user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="new_form">Create A User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% @newest_posts.each do |post| %>
  <div class="col-xs-offset-0 col-sm-offset-7 col-xs-12 col-sm-4 latest_user_posts">
    <%= link_to post.discuss.topic.subject.forum.title, forum_path(id: post.discuss.topic.subject.forum) %> - 
    <%= link_to post.discuss.topic.subject.title, forum_subject_path(forum_id: post.discuss.topic.subject.forum, id: post.discuss.topic.subject) %> - 
    <%= link_to post.discuss.topic.title, forum_subject_topic_path(forum_id: post.discuss.topic.subject.forum, subject_id: post.discuss.topic.subject, id: post.discuss.topic) %> 
    <br>
    <%= link_to post.discuss.title, forum_subject_topic_discuss_posts_path(forum_id: post.discuss.topic.subject.forum, subject_id: post.discuss.topic.subject, topic_id: post.discuss.topic, discuss_id: post.discuss) %>
  </div>
  <div class="newest_post_wrapper post_wrapper col-xs-offset-0 col-sm-offset-7 col-xs-12 col-sm-4">
    <div class="col-xs-4 user_post_time">
     <%= time_ago_in_words(post.updated_at) %> ago
    </div>
    <div class="col-xs-8 user_post_area">
  	 <%= post.description %>
    </div>
  </div> 
<% end %>

<div>
</div>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', :back %>