config/routes.rb
Zero::Application.routes.draw do
  resources :events

  devise_for :users
  resources :users

  resources :forums do 
    resources :subjects do
      resources :topics do
        resources :discusses do
          resources :posts
        end
      end
    end
  end
  
  resources :event_calendar
  resources :events do
    resources :rsvps
  end
  resources :home
  
  root 'home#index'

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: [:scoped, :slugged], scope: :forum
	
	belongs_to :forum, touch: true
	has_many :topics
	belongs_to :user
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_forum_from_forum_id
  before_action :set_newest
  before_action :set_user_from_current_user
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = @forum.subjects.order('title ASC')
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new(forum_id: @forum)
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = @forum.subjects.new(subject_params)
    @subject.user = @user


    respond_to do |format|
      if @subject.save
        format.html { render action: 'show'}
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_newest
        @newest = Discuss.friendly.find(:all, order: "updated_at", limit: 5).reverse
  end


  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subjects, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = @forum.subjects.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:forum_id, :title, :description, :username)
    end
end

app/views/subjects/_form.html.erb
<%= form_for [@forum, @subject] do |f| %>
  <div class="col-xs-offset-0 col-sm-offset-2 col-xs-12 col-sm-8 form_body">
    <div class="field">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br>
      <%= f.text_area :description, size: "35x5" %>
    </div>
  </div>
  <div class="actions form_submit col-xs-offset-0 col-sm-offset-2 col-xs-12 col-sm-8">
    <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1 class="new_form">Edit A Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_subjects_path %>

app/views/subjects/index.html.erb
<div class="forum_wrapper col-xs-offset-0 col-sm-offset-1 col-xs-12 col-sm-10">
  <% @subjects.each do |subject| %>
    <div class="row forum_row">
      <div class="col-xs-2 forum_user">
        <%= link_to subject.user.username, user_path(subject.user) %>
      </div>
      <div class="col-xs-8 forum_area">
        <%= link_to subject.title, forum_subject_topics_path(subject_id: subject.slug) %>
        <br>
        <div>
          <%= subject.description %>
        </div>
      </div> 
      <div class="col-xs-2 forum_time">
        <%= time_ago_in_words(subject.updated_at) %> ago
        <% if current_user && current_user.admin %>
          <br>
          <%= link_to 'Destroy', forum_subject_path(id: subject.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'Edit', edit_forum_subject_path(id: subject.id) %>
        <% end %>
      </div>
      </br>
    </div>
  <% end %>
  <br>
</div>
<% if current_user %>
  <a href="<%= new_forum_subject_path %>" class="btn btn-default col-sm-offset-10">New Subject</a>
<% end %>

app/views/subjects/new.html.erb
<h1 class="new_form">Create A Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', new_forum_subject_path(params[:forum_id]) %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> forum:</strong>
  <%= @subject.forum_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @subject.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>

<%= link_to 'Edit', edit_forum_subject_path(@forum, @subject) %> |
<%= link_to 'Back', forum_subjects_path %>