config/routes.rb
Zero::Application.routes.draw do
  resources :events

  devise_for :users
  resources :users

  resources :forums do 
    resources :subjects do
      resources :topics do
        resources :discusses do
          resources :posts
        end
      end
    end
  end
  
  resources :event_calendar
  resources :events do
    resources :rsvps
  end
  resources :home
  
  root 'home#index'

  

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
	friendly_id :title, use: [:scoped, :slugged], scope: :discuss
	
	belongs_to :discuss, touch: true
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_subject_from_subject_id
  before_action :set_forum_from_forum_id
  before_action :set_topic_from_topic_id
  before_action :set_discuss_from_discuss_id
  before_action :set_user_from_current_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @discuss.posts.order('created_at ASC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new(discuss_id: @discuss)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @discuss.posts.new(post_params)
    @post.user = @user

    respond_to do |format|
      if @post.save
        format.html { redirect_to forum_subject_topic_discuss_posts_path(discuss_id: @discuss) }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @discuss.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:discuss_id, :title, :description, :created_at, :updated_at, :username)
    end
end

app/views/posts/_form.html.erb
<%= form_for [@forum, @subject, @topic, @discuss, @post] do |f| %>
	<div class="forum_wrapper post_wrapper new_post col-xs-offset-0 col-sm-offset-3 col-xs-12 col-sm-6"> 
		<div class="field">
			<%= f.label :description %>
			<br>
			<%= f.text_area :description, size: "20x5" %>
		</div>
	</div>
	<div class="actions form_submit col-xs-offset-0 col-sm-offset-8 col-xs-12 col-sm-2">
		<%= f.submit %>
	</div>
<% end %>

app/views/posts/_new.html.erb
<%= form_for [@forum, @subject, @topic, @discuss, Post.new] do |f| %>
	<div class="forum_wrapper post_wrapper new_post col-xs-offset-0 col-sm-offset-3 col-xs-12 col-sm-6"> 
		<div class="field">
			<%= f.label :description %>
			<br>
			<%= f.text_area :description, size: "20x5" %>
		</div>
	</div>
	<div class="actions form_submit col-xs-offset-0 col-sm-offset-8 col-xs-12 col-sm-2">
		<%= f.submit %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h2 class="new_form"> <%= @discuss.title %> </h2>

<div class="forum_wrapper post_wrapper col-xs-offset-0 col-sm-offset-3 col-xs-12 col-sm-6">
  <div class="row post_row">
    <div class="col-xs-2 forum_user">
      <%= link_to @discuss.user.username, @discuss.user %>
    </div>
    <div class="col-xs-7 forum_area">
      <%= @discuss.description %>
    </div>
    <div class="col-xs-3 forum_time">
      <%= time_ago_in_words(@discuss.created_at) %> ago
      <br>
      <%= link_to 'Destroy', forum_subject_topic_discuss_path(id: @discuss.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit', edit_forum_subject_topic_discuss_path(id: @discuss.id) %>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
<div class="forum_wrapper post_wrapper col-xs-offset-0 col-sm-offset-3 col-xs-12 col-sm-6">  
  <div class="row post_row">
    <div class="col-xs-2 forum_user">
      <%= link_to post.user.username, user_path(post.user) %>
    </div>
    <div class="col-xs-7 forum_area">
      <%= post.description %>
    </div> 
    <div class="col-xs-3 forum_time">
      <%= time_ago_in_words(post.updated_at) %> ago
      <% if current_user && current_user.admin %>
        <%= link_to 'Destroy', forum_subject_topic_discuss_post_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_forum_subject_topic_discuss_post_path(id: post.id) %>
      <% end %>
    </div>
    <br>
  </div>
</div>
<% end %>
  <br>
<% if current_user %>
   <%= render 'new' %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_subject_topic_discuss_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>